### ISSUE TITLE
link to bug tracker in Support menu

### ISSUE THREAD

**Issue by fastfasterfastest** [jquery/jquery-wp-content#220]
I think it would be helpful if the Support menu (upper right) contained a link (or links) to "Browse or Submit bugs".  If possible it would be nice if such link was "context sensitive" so when you are on jquery.com it takes you to the jquery bug tracker, when you are on jqueryui.com it takes you to the jqueryui bug tracker, etc.

**Comment by Krinkle** [comment]
In https://github.com/jquery/jquery.com/pull/237, we consolidated many support pages into https://jquery.com/support/ which is linked from the "Support" menu and includes a section at the bottom about bug reports.

> https://jquery.com/support/#found-a-bug
> Found a bug?
> For reporting bugs in libraries, documentation, or content, the project's GitHub issues tracker should be used. All jQuery projects can be found at https://github.com/jquery

<img width="190" alt="Screenshot" src="https://github.com/jquery/jquery-wp-content/assets/156867/8b10dd0a-4b5b-43e7-bc52-d0520e86a987">

I propose adding a "Report a bug" explicilty in the Support menu, but am unsure which of these three destinations to pick:

1. <https://github.com/jquery/> - Let the user land here, and pick their repository, and follow the same discovery path that probably most people need to follow regardless, assuming our git repo is a fairly common landing place. They then find their way to "Issues", potentially performing a search first, then click "New issue". There, now three steps further, they are greeted with a template about minimal test cases, and latest jQuery version etc.
2. https://contribute.jquery.org/bug-reports/ - This contains a more fleshed out version of the information in the template, with the benefit of receiving it immediately upon the jquery.com menu link, instead of after several steps. Also, on this page starts with how to ask for support from chat/StackOverlow first. Do we still prefer that? Also, the URLs are actually clickable/linked so people are more likely to follow "how to reduce a test case" and e.g. use CodePen/JSBin. This web page then sends you to https://github.com/jquery/jquery/issues once done.
3. <https://jquery.com/support/> - Linking this would take the recommendation to ask for support first and literally drop people there first. If they go past the Learning Center, API Docs, Chat, StackOverflow, they then find the "Found a bug" heading and go to https://github.com/jquery from there.

Thoughts?

**Comment by Krinkle** [comment]
Summary of jquery_dev Matrix chat today:

* Between these three links, @timmywil prefers https://contribute.jquery.org/bug-reports/.
* Timmy raisees that despite this page doing a good job to discourage invalid bug reports, adding exposure from a prominent link on the site, may increase bug reports, especially invalid ones, beyond our capacity to triage (the team isn't as large as it used to be).
* @mgol suggests we try it. We agree to try it and see how it goes.
