### ISSUE TITLE
Make footer credit logos HiDPI-friendly

### ISSUE THREAD

**Issue by melchoyce** [jquery/jquery-wp-content#370]
They're blurry on retina/HiDPI screens:

<img width="499" alt="screen shot 2015-07-26 at 3 23 29 pm" src="https://cloud.githubusercontent.com/assets/2846578/8895482/60137fde-33aa-11e5-8ba3-74a8a2416409.png">

**Comment by melchoyce** [comment]
There are two options here:

1. Add in 2x png versions of the logos
2. Swap the pngs out for [inline SVGs](https://css-tricks.com/using-svg/)

2x pngs are easiest, and already the convention being used. However, this could be a good place to try introducing inline SVGs, which will be more future-proof.

What kind of browser support does jquery-wp-content maintain?

**Comment by arthurvr** [comment]
> What kind of browser support does jquery-wp-content maintain?

IE8+

**Comment by jdorfman** [comment]
MaxCDN and Wordpress logos are in Font Awesome:
* http://fontawesome.io/icon/maxcdn/
* http://fontawesome.io/icon/wordpress/

Since jquery.com already uses Font Awesome, this would be as easy as replacing the logos with:

* `<i class="fa fa-maxcdn"></i>`
* `<i class="fa fa-wordpress"></i>`

As for Media Temple, a [request can be made](https://github.com/FortAwesome/Font-Awesome/issues).

**Comment by melchoyce** [comment]
Looks like there's a Media Temple issue already: https://github.com/FortAwesome/Font-Awesome/issues/1531

Font Awesome would work well for the other two. Maybe for now we can replace MaxCDN and WordPress with Font Awesome, and add a 2x png for Media Temple? Happy to make a PR.

**Comment by Krinkle** [comment]
Done in https://github.com/jquery/jquery-wp-content/commit/28542b5616895cba4ac4fa41144abd05b5087a04.
